import { Word } from '@/models/word'

export const verbsToIng: Array<Word> = [
  {
    id: 1,
    wordValue: 'afford',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 2,
    wordValue: 'demand',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 3,
    wordValue: 'like',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 4,
    wordValue: 'pretend',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 5,
    wordValue: 'agree',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 6,
    wordValue: 'fail',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 7,
    wordValue: 'love',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 8,
    wordValue: 'promise',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 9,
    wordValue: 'arrange',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 10,
    wordValue: 'forget',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 11,
    wordValue: 'manage',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 12,
    wordValue: 'refuse',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 13,
    wordValue: 'ask',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 14,
    wordValue: 'hate',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 15,
    wordValue: 'mean (= intend)',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 16,
    wordValue: 'remember',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 17,
    wordValue: 'begin',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 18,
    wordValue: 'help',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 19,
    wordValue: 'need',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 20,
    wordValue: 'start',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 21,
    wordValue: 'choose',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 22,
    wordValue: 'hope',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 23,
    wordValue: 'offer',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 24,
    wordValue: 'try',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 25,
    wordValue: 'continue',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 26,
    wordValue: 'intend',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 27,
    wordValue: 'plan',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 28,
    wordValue: 'want',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 29,
    wordValue: 'decide',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 30,
    wordValue: 'learn',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 31,
    wordValue: 'prefer',
    combinedTranslation: 'to',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 32,
    wordValue: 'admit',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 33,
    wordValue: 'deny',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 34,
    wordValue: 'finish',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 34,
    wordValue: 'mind',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 35,
    wordValue: 'avoid',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 36,
    wordValue: 'dislike',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 37,
    wordValue: 'give up',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 38,
    wordValue: 'miss',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 39,
    wordValue: '(can’t) help',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 40,
    wordValue: 'enjoy',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 41,
    wordValue: 'imagine',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 42,
    wordValue: 'practise',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 43,
    wordValue: '(can’t) stand',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 44,
    wordValue: 'fancy',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 45,
    wordValue: 'involve',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 46,
    wordValue: 'put off',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 47,
    wordValue: 'consider',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 48,
    wordValue: 'feel like',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 49,
    wordValue: 'keep (on)',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 50,
    wordValue: 'risk',
    combinedTranslation: 'ing',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 51,
    wordValue: 'let',
    combinedTranslation: '-',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 52,
    wordValue: 'make',
    combinedTranslation: '-',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
  {
    id: 53,
    wordValue: 'help',
    combinedTranslation: '-',
    transcription: '',
    picture: '',
    pronunciation: '',
    created: 0,
    added: 0,
  },
]
