name: CI

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.7.0

      - run: pnpm install
      - run: pnpm tsc
      - run: pnpm lint
      - run: pnpm test:ci

  e2e:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.7.0

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm run e2e:ci

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 2
